### ISSUE TITLE
arm8 docker buid?

### ISSUE THREAD

**Issue by houdini69** [nanawel/our-shopping-list#14]
Would it be possible to have an arm8 version of our-shopping-list?

**Comment by richardneish** [comment]
Is this just using "https://hub.docker.com/r/arm64v8/node/" for the Docker images?  I haven't done it before, but it looks like it should be a small change, since Node on Arm64v8 is a supported architecture for the official Node image.  @houdini69 can you try and submit a PR if you get something working?

**Comment by houdini69** [comment]
> Is this just using "https://hub.docker.com/r/arm64v8/node/" for the Docker images? I haven't done it before, but it looks like it should be a small change, since Node on Arm64v8 is a supported architecture for the official Node image. @houdini69 can you try and submit a PR if you get something working?

I'm just an end user and don't know how to build a docker image. Therefore, I leave it to someone more knowledgeable than me to test your suggestion!

**Comment by houdini69** [comment]
I finally tried to build docker image on my Debian Bullseye server and successfully get running container with docker-compose. Container has an "healthy" status. However, I couldn't connect in my LAN on listening port.

My docker-compose configuration
`version: '3.2'

services:
  app:
    image: our-shopping-list:latest
    restart: always
    ports:
      - '8100:8100'
    environment:
      # Default values below
      VUE_APP_I18N_LOCALE: fr
      VUE_APP_I18N_FALLBACK_LOCALE: fr
      VUE_APP_I18N_FORCE_LOCALE: 0
      VUE_APP_SINGLEBOARD_MODE: 0
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:`

How to debug?

**Comment by nanawel** [comment]
Hi @houdini69 
That's great news, thanks for your time.

Could you use the ["three backticks" syntax](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) to format your YAML please? That would help readbility a lot.

About your port issue, that seems like an easy detail to fix: you're using `8100` for the internal port while the Node server listens on `8080` by default.
So both alternatives below should work in your `docker-compose.yml` if you absolutely need your host to listen on `8100` on its interfaces:

```yaml
...
    ports:
      - '8100:8080'
```
or
```yaml
...
    ports:
      - '8100:8100'
    environment:
      LISTEN_PORT: 8100
```

**Comment by houdini69** [comment]
here it is my original docker-compose.yml

```
version: '3.2'

services:
  app:
    image: our-shopping-list:latest
    restart: always
    ports:
      - '8100:8100'
    environment:
      # Default values below
      VUE_APP_I18N_LOCALE: fr
      VUE_APP_I18N_FALLBACK_LOCALE: fr
      VUE_APP_I18N_FORCE_LOCALE: 0
      VUE_APP_SINGLEBOARD_MODE: 0
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:

```
I'm going to try your suggestion.
