### ISSUE TITLE
Tons of calls/requests to mongodb

### ISSUE THREAD

**Issue by gouthamravee** [nanawel/our-shopping-list#28]
The app frontend seems to call for mongodb a lot. I see about 2000 - 3000 requests every 10 minutes to `mongodb` from the host running the `our-shopping-list` container. Nothing else on that host uses mongodb. 

Any way I can reduce these calls? 

Here's my docker-compose

```
services:
  app:
    image: ourshoppinglist/our-shopping-list:latest
    restart: always
    ports:
      - '8086:8080'
    environment:
      TZ: America/New_York
      # Default values below (See README for more)
      VUE_APP_I18N_LOCALE: en
      VUE_APP_I18N_FALLBACK_LOCALE: en
      VUE_APP_I18N_FORCE_LOCALE: 0
      VUE_APP_SINGLEBOARD_MODE: 0
    # You may want to use a .env file instead
    #env_file:
    #  - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #  - ./robots.txt:/app/robots.txt:ro   # See README
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
```
